// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package storage

type Report struct {
	ID              string
	Income          float64
	Expense         float64
	NetSaving       float64
	BudgetAmount    float64
	BudgetSpent     float64
	RemainingBudget float64
}
