// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package storage

type Budget struct {
	ID       string
	UserID   string
	Category string
	Amount   float64
	Spent    float64
	Currency string
}
