// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package storage

type Transaction struct {
	ID       string
	UserID   string
	Type     string
	Category string
	Currency string
	Amount   float64
	Date     string
}
